// @ts-nocheck
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * App represents a Pipedream app/integration
 */
export class App {
    "id": string;
    "name_slug": string;
    "name": string;
    "description": string;
    "auth_type": string;
    "img_src": string;
    "categories": string[];
    "featured_weight": number;

    /** Creates a new App instance. */
    constructor($$source: Partial<App> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name_slug" in $$source)) {
            this["name_slug"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("auth_type" in $$source)) {
            this["auth_type"] = "";
        }
        if (!("img_src" in $$source)) {
            this["img_src"] = "";
        }
        if (!("categories" in $$source)) {
            this["categories"] = [];
        }
        if (!("featured_weight" in $$source)) {
            this["featured_weight"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new App instance from a string or object.
     */
    static createFrom($$source: any = {}): App {
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("categories" in $$parsedSource) {
            $$parsedSource["categories"] = $$createField6_0($$parsedSource["categories"]);
        }
        return new App($$parsedSource as Partial<App>);
    }
}

/**
 * ConnectedAccount represents an account connected via Pipedream
 */
export class ConnectedAccount {
    "id": string;
    "name": string;
    "external_id"?: string;
    "healthy": boolean;
    "dead": boolean;
    "app": ConnectedAccountApp;
    "created_at": string;
    "updated_at"?: string;

    /** Creates a new ConnectedAccount instance. */
    constructor($$source: Partial<ConnectedAccount> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("healthy" in $$source)) {
            this["healthy"] = false;
        }
        if (!("dead" in $$source)) {
            this["dead"] = false;
        }
        if (!("app" in $$source)) {
            this["app"] = (new ConnectedAccountApp());
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectedAccount instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectedAccount {
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("app" in $$parsedSource) {
            $$parsedSource["app"] = $$createField5_0($$parsedSource["app"]);
        }
        return new ConnectedAccount($$parsedSource as Partial<ConnectedAccount>);
    }
}

/**
 * ConnectedAccountApp represents the app info nested in a connected account
 */
export class ConnectedAccountApp {
    "name_slug": string;
    "name": string;
    "img_src": string;

    /** Creates a new ConnectedAccountApp instance. */
    constructor($$source: Partial<ConnectedAccountApp> = {}) {
        if (!("name_slug" in $$source)) {
            this["name_slug"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("img_src" in $$source)) {
            this["img_src"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectedAccountApp instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectedAccountApp {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectedAccountApp($$parsedSource as Partial<ConnectedAccountApp>);
    }
}

/**
 * TokenResponse represents a Pipedream Connect token
 */
export class TokenResponse {
    "token": string;
    "expires_at": string;
    "connect_link_url": string;

    /** Creates a new TokenResponse instance. */
    constructor($$source: Partial<TokenResponse> = {}) {
        if (!("token" in $$source)) {
            this["token"] = "";
        }
        if (!("expires_at" in $$source)) {
            this["expires_at"] = "";
        }
        if (!("connect_link_url" in $$source)) {
            this["connect_link_url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TokenResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): TokenResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TokenResponse($$parsedSource as Partial<TokenResponse>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = ConnectedAccountApp.createFrom;
