// @ts-nocheck
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct holds application state and dependencies
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.ts";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "./settings/models.ts";

/**
 * CheckAccessibility checks if accessibility permission is granted
 */
export function CheckAccessibility(): $CancellablePromise<boolean> {
    return $Call.ByID(1492572881);
}

/**
 * CheckMicrophone checks the microphone permission status
 * Returns: "granted", "denied", "not_asked", "restricted", "unknown"
 */
export function CheckMicrophone(): $CancellablePromise<string> {
    return $Call.ByID(2449451919);
}

/**
 * DownloadModel downloads a whisper model
 */
export function DownloadModel(modelName: string): $CancellablePromise<void> {
    return $Call.ByID(2592961078, modelName);
}

/**
 * GetContinuousState returns the current continuous conversation state
 */
export function GetContinuousState(): $CancellablePromise<string> {
    return $Call.ByID(2668643057);
}

/**
 * GetLanguages returns supported transcription languages
 */
export function GetLanguages(): $CancellablePromise<string[]> {
    return $Call.ByID(3533302854).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetSettings returns the current application settings.
 */
export function GetSettings(): $CancellablePromise<settings$0.Settings> {
    return $Call.ByID(2554697378).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetSilenceDurationMs returns the current silence duration setting.
 */
export function GetSilenceDurationMs(): $CancellablePromise<number> {
    return $Call.ByID(361306074);
}

/**
 * Greet returns a greeting message - example method exposed to frontend
 */
export function Greet(name: string): $CancellablePromise<string> {
    return $Call.ByID(2659711170, name);
}

/**
 * IsContinuousMode returns whether continuous listening mode is active
 */
export function IsContinuousMode(): $CancellablePromise<boolean> {
    return $Call.ByID(2049118753);
}

/**
 * IsConversationConfigured returns whether the voice chat APIs are configured.
 */
export function IsConversationConfigured(): $CancellablePromise<boolean> {
    return $Call.ByID(1439924430);
}

/**
 * IsConversationMode returns whether conversation mode is active.
 */
export function IsConversationMode(): $CancellablePromise<boolean> {
    return $Call.ByID(1515400133);
}

/**
 * IsOverlayVisible returns whether the overlay is currently visible
 */
export function IsOverlayVisible(): $CancellablePromise<boolean> {
    return $Call.ByID(2490546543);
}

/**
 * IsReady returns whether the transcription service is initialized
 */
export function IsReady(): $CancellablePromise<boolean> {
    return $Call.ByID(1609617756);
}

/**
 * IsTranscribing returns whether transcription is currently active
 */
export function IsTranscribing(): $CancellablePromise<boolean> {
    return $Call.ByID(2628295481);
}

/**
 * OpenAccessibilitySettings opens System Settings to the Accessibility pane
 */
export function OpenAccessibilitySettings(): $CancellablePromise<void> {
    return $Call.ByID(2298907446);
}

/**
 * OpenMicrophoneSettings opens System Settings to the Microphone pane
 */
export function OpenMicrophoneSettings(): $CancellablePromise<void> {
    return $Call.ByID(2078724176);
}

/**
 * ProcessVoiceInput takes a transcribed user message, sends it to the LLM,
 * synthesizes the response with TTS, and emits events for the frontend.
 */
export function ProcessVoiceInput(text: string): $CancellablePromise<void> {
    return $Call.ByID(3379769464, text);
}

/**
 * RegisterHotkeys sets up the global hotkeys after the app window is ready
 */
export function RegisterHotkeys(): $CancellablePromise<void> {
    return $Call.ByID(1337292899);
}

/**
 * RequestMicrophonePermission triggers the system microphone permission dialog
 */
export function RequestMicrophonePermission(): $CancellablePromise<void> {
    return $Call.ByID(3230311345);
}

/**
 * ResizeOverlay resizes the overlay window and re-positions it at the bottom-left
 */
export function ResizeOverlay(width: number, height: number): $CancellablePromise<void> {
    return $Call.ByID(2507787999, width, height);
}

/**
 * SetApp injects the Wails application reference
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(4256893662, app);
}

/**
 * SetElevenLabsAPIKey updates the ElevenLabs API key in settings and service.
 */
export function SetElevenLabsAPIKey(key: string): $CancellablePromise<string> {
    return $Call.ByID(411033165, key);
}

/**
 * SetElevenLabsVoiceID updates the ElevenLabs voice ID in settings and service.
 */
export function SetElevenLabsVoiceID(voiceID: string): $CancellablePromise<string> {
    return $Call.ByID(1488636969, voiceID);
}

/**
 * SetGeminiAPIKey updates the Gemini API key in settings and service.
 */
export function SetGeminiAPIKey(key: string): $CancellablePromise<string> {
    return $Call.ByID(3562040091, key);
}

/**
 * SetOverlayWindow registers the overlay window
 */
export function SetOverlayWindow(window: application$0.WebviewWindow | null): $CancellablePromise<void> {
    return $Call.ByID(2833066025, window);
}

/**
 * SetSelectedLanguage sets the language for transcription
 */
export function SetSelectedLanguage(language: string): $CancellablePromise<void> {
    return $Call.ByID(2460770088, language);
}

/**
 * SetSilenceDurationMs updates the silence duration for VAD in settings and service.
 */
export function SetSilenceDurationMs(durationMs: number): $CancellablePromise<string> {
    return $Call.ByID(2930594590, durationMs);
}

/**
 * SetWindow registers the main window
 */
export function SetWindow(window: application$0.WebviewWindow | null): $CancellablePromise<void> {
    return $Call.ByID(3654517795, window);
}

/**
 * StartConversation enters conversation mode. In this mode, hotkey-triggered
 * transcriptions are routed to the LLM for a conversational reply, which is
 * then synthesized to speech via TTS and sent to the frontend for playback.
 */
export function StartConversation(): $CancellablePromise<string> {
    return $Call.ByID(81776248);
}

/**
 * StartTranscription begins recording and transcription
 */
export function StartTranscription(language: string): $CancellablePromise<string> {
    return $Call.ByID(805476209, language);
}

/**
 * StopConversation exits conversation mode and clears history.
 */
export function StopConversation(): $CancellablePromise<string> {
    return $Call.ByID(2630667022);
}

/**
 * StopTranscription stops recording and processes the audio
 */
export function StopTranscription(): $CancellablePromise<string> {
    return $Call.ByID(293876119);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = settings$0.Settings.createFrom;
