// @ts-nocheck
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Settings holds application configuration.
 */
export class Settings {
    "geminiApiKey": string;
    "elevenLabsApiKey": string;
    "elevenLabsVoiceId": string;
    "pressAndTalkHotkey": string;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("geminiApiKey" in $$source)) {
            this["geminiApiKey"] = "";
        }
        if (!("elevenLabsApiKey" in $$source)) {
            this["elevenLabsApiKey"] = "";
        }
        if (!("elevenLabsVoiceId" in $$source)) {
            this["elevenLabsVoiceId"] = "";
        }
        if (!("pressAndTalkHotkey" in $$source)) {
            this["pressAndTalkHotkey"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Settings($$parsedSource as Partial<Settings>);
    }
}
