// @ts-nocheck
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AvatarInfo represents a generated custom avatar.
 */
export class AvatarInfo {
    "id": string;
    "path": string;

    /**
     * base64 PNG
     */
    "thumbnail": string;
    "createdAt": number;

    /** Creates a new AvatarInfo instance. */
    constructor($$source: Partial<AvatarInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("thumbnail" in $$source)) {
            this["thumbnail"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AvatarInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): AvatarInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AvatarInfo($$parsedSource as Partial<AvatarInfo>);
    }
}
